### PR TITLE
Create gnome-shell.css

### PR DESCRIPTION
**Pull request by vanillajonathan**
Very basic gnome-shell theme. Derives from the standard themes and does some basic overrides.

### CODE REVIEW

**Comment by satya164** [comment]
@ochosi Do we want a Gnome Shell theme? Considering the maintenance overhead?

**Comment by ochosi** [comment]
My general problem with a gnome-shell theme is that I don't use gnome-shell, so I could neither test nor maintain it. If someone steps up and vouches not only to design the gnome-shell theme but also to maintain it consequently, I'd be fine with that.

**Comment by vanillajonathan** [comment]
Right now the maintenance overhead should be quite low as it currently a quite basic theme which derives from the standard theme and just adds some rules to overwrite some properties in the inherited/parent theme.

On the other hand, I don't know if it lives up to the artist's vision, style and design philosophy for Greybird.

To me it improves visual consistency with GNOME Shell and Greybird. I hope it could be useful for someone else too.

**Comment by ochosi** [comment]
Well yes, that's another aspect, I can't really test it.
@satya164 Thoughts on merging the theme as is?

**Comment by satya164** [comment]
I'll test and merge.

Satyajit Sahoo
UX Designer
Behance Profile <https://www.behance.net/satyajitha28c7>

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by ochosi** [comment]
@satya164 Hm, so what should we do with this one? Also, how much does Gnome Shell change from version to version and with what versions would the MR work? In other words: would we have to update this for every Gnome/Gtk+ release?

**Comment by satya164** [comment]
@ochosi GNOME Shell changes a lot from version to version AFAIK. I don't think I can maintain this.

**Comment by ochosi** [comment]
Ok, then let's close this pull request. Thanks for your effort though, @vanillajonathan

**Pull request closed without merging**
