### PR TITLE
Enlarged button images for better spacing and more usability

### PR DESCRIPTION
**Pull request by RalphBike**

### CODE REVIEW

**Comment by ochosi** [comment]
@RalphBike The branch cannot be merged cleanly, you probably have to rebase it on top of Greybird master.

**Comment by RalphBike** [comment]
Hi, thanks for the hint, rebase was what I was looking for. Please try again.

**Comment by ochosi** [comment]
Some of the *pressed.xpm icons are missing some spaces in their top line, which is why they're rendered weirdly, as you can see in this screenshot: http://i.imgur.com/GeCPUIA.png

**Comment by RalphBike** [comment]
Fixed. Please check.

**Comment by ochosi** [comment]
Thanks, looks good now!

**Pull request merged**
