### PR TITLE
Better button positions in fullscreen

### PR DESCRIPTION
**Pull request by RalphBike**
Moved the buttons a bit further away from the border when in fullscreen mode.

### CODE REVIEW

**Comment by ochosi** [comment]
Hi, while your setup looks better one important feature that goes missing is just dragging the mouse wildly to the top right corner (or left, if you have close there) and hitting the left mouse-button to close the window. This is especially nice with smaller buttons, as used in the compact version of the theme.

That was a design decision that the normal Greybird xfwm4 theme also follows (although arguably it looks better there because the buttons have more padding).

What could be done is resizing the buttons to add the padding in the button itself and then reducing button_spacing=10 to something smaller to reach both the desired effect and keep the current behavior.

**Comment by RalphBike** [comment]
Hi Simon, 

thanks for the feedback. I got your point and think you are right on a functional level. Let me think about it and maybe try it. Would you support that change if I implement it and it looks okay? That would mean to touch all those buttons. Or only the close-button?

Are you fine with the look I achieved? The compact skin is my favorite skin besides for the non-harmonic position of the close button very close to the edge.

Best, Ralph

BTW, if you speak german, we could also switch. As you like....

**Comment by ochosi** [comment]
I think in order to make the result consistent (buttons can be reordered and you will always want the same padding between them) all would have to be resized.

I visually like your proposal and think it'd be an improvement, so if you wanna go ahead and resize them I'll definitely accept the pull request

**Comment by RalphBike** [comment]
Sounds good, however I do not want to promise anything right now (lots of manual work). 

Question: Resizing by how many pixels? 

Spacing is 10px at the moment and I do not see a reason why not to use most of it as this would also increase usability by easer-to-hit buttons. So I would enlarge the buttons from 12x18 px to 20x18 px which would leave 2 px of gap in between and adjust offsets accordingly. What do you think? More gap or less?

**Comment by ochosi** [comment]
Yes, I would say the gaps are not really necessary so feel free to fill those up with the buttons. So I'd say your proposal sounds alright.

**Pull request closed without merging**
