### PR TITLE
Fix label styles for xfdesktop 4.19

### PR DESCRIPTION
**Pull request by andreldm**
Xfdesktop from git master (54f5e219)

| | Light      | Dark |
| ---| ----------- | ----------- |
| Before | image | image |
| After| image | image |

### CODE REVIEW

**Comment by andreldm** [comment]
@kelnos when you have the time, please take a look at this PR, I don't remember what was the rationale for the changes you introduced to xfdesktop in 4.19.x, what reminded me about this issue is because I stopped using dark themes and xfdesktop when unfocused looks terrible.

**Comment by andreldm** [comment]
@kelnos thanks for the response, just keep in mind that your changes also affect Adwaita, that's one of the themes we (Xfce) try to look ok, but I doubt its maintainers will add a style override for xfdesktop.

**Comment by kelnos** [comment]
Understood, and thanks for the warning about Adwaita.

Another option (instead of doing style overrides in the theme like you've done here: as I said, I plan to make a bunch of these settable in the desktop settings panel -- would it make sense to set the default values for those to make things look as close as possible to what the 4.18 styling rules do?  That would make it less of a shock for people updating, but they can still play around with the styles in the settings dialog (and even disable the overrides entirely so it uses the theme settings, if they want).

**Comment by andreldm** [comment]
Sorry for the late reply, IMHO this is about styling not setting/preferences, but providing minimally good-looking default is still better than relying on themes to catch up.

**Comment by kelnos** [comment]
Sure, that makes sense.

The thing is, though 4.19.x now actually is using _the_ default styling for an icon view, according to the theme.  Unless I've made some (more) mistakes, the style classes and widget state flags during rendering now actually get set correctly for each component that gets drawn, which was not the case before.  I think that's really the only sane way to do it.

When I originally wrote `XfdesktopIconView` ~15 years ago, I had no idea what I was doing when it came to styles and how the widget states mapped to what was shown on the screen, so I just tried a bunch of things until I ended up with something that looked ok, without really understanding why.  Of course, that was on GTK2; someone else did the GTK3 porting, and didn't really fix my mistakes (not their fault, of course).

Now, 4.19 may not look super great; I agree that your "Before" screenshots aren't the best, and the "After" ones look much better.  If there's a way we can get xfdesktop to look like that by default, but without doing insane/incorrect things with the style classes or widget states while drawing, then sure, let's do that.  But if not, then I don't think I want to change anything.

So it's up to you if you want to put (more?) xfdesktop-specific things into themes at this point.  But consider also that the 4.20 release isn't for another year, and it's possible I/we might find a still-correct but better-looking way to do the drawing that wouldn't require that every theme have styles added in order to look good.  I'm working on some other projects right now, but I'm hoping to get back to xfdesktop in a few months.

**Comment by andreldm** [comment]
Alright, I agree, let's sit on this issue for the time being.

**Comment by alexxcons** [comment]
This seems to fix the issue:

```
XfdesktopIconView.view {
  background-color: transparent;
}

XfdesktopIconView.view.label:selected {
  background-color: @theme_selected_bg_color;
}
```
(Copied from https://gitlab.xfce.org/xfce/xfdesktop/-/issues/323#note_95050)

**Comment by andreldm** [comment]
@alexxcons unfortunately that didn't fix the problem for me, if xfdesktop does not have the focus labels will be ugly as shown in the first comment.

I'm inclined to merge this PR, I checked and there are no regressions when using xfdesktop 4.18, but before that, if you have the time, please let me know if it works well for you.

**Comment by kelnos** [comment]
@andreldm https://gitlab.xfce.org/xfce/xfdesktop/-/commit/80e3c8c65840cdcc3b942b3fab7dc08f4f8c60ea didn't fix the problem without additional theme changes?

**Comment by alexxcons** [comment]
> @alexxcons unfortunately that didn't fix the problem for me, if xfdesktop does not have the focus labels will be ugly as shown in the first comment.
> 
> I'm inclined to merge this PR, I checked and there are no regressions when using xfdesktop 4.18, but before that, if you have the time, please let me know if it works well for you.

Using the latest version of xfdesktop, it works fine for me to configure the background color in `xfdesktop-settings`. So I don't think we need a fix greybird anymore. (I would have used alpha=0 as default for the setting, though that probably is controversial)

Using that css snippet caused some rubber-banding trouble for me: https://gitlab.xfce.org/xfce/xfdesktop/-/issues/335 ... meanwhile, I don't use the snippet any more and things work well for me.

**Comment by andreldm** [comment]
@kelnos out of the box no, if I set a background color in settings yes, but I don't think that's desirable.

> So I don't think we need a fix for greybird anymore. (I would have used alpha=0 as default for the new setting, though that probably is controversial)

@alexxcons if you leave settings at their default values, do you see the issue I'm trying to fix?

**Comment by kelnos** [comment]
> out of the box no, if I set a background color in settings yes, but I don't think that's desirable.

Oh, that's odd, I thought that change should have fixed things up.  Do you know what needs to be done to the fallback theme to fix it?  I'd rather just fix it there.

**Comment by alexxcons** [comment]
> @alexxcons if you leave settings at their default values, do you see the issue I'm trying to fix?

Yea, without using custom background labels, I still see the described issue. I need to set background color to (0,0,0,0) to make things "nice" for me (I as well modify the text color, but that depends on the used wallpaper)

**Comment by andreldm** [comment]
> Oh, that's odd, I thought that change should have fixed things up. Do you know what needs to be done to the fallback theme to fix it? I'd rather just fix it there.
> 
> I'm surprised it doesn't work as-is, since both `XfdesktopIconView.view.label` and `XfdesktopIconView.view.label:backdrop` have `background-color: transparent` now. Are there other non-selected states I'm missing?

The fallback doesn't work because it is never applied for Greybird or any theme containing `XfdesktopIconView`.

The problem comes from [here](https://github.com/shimmerproject/Greybird/blob/ffa98463814c3012440f8ef1002acc8b8665ba0a/light/gtk-3.0/_common.scss#L101-L110), I have tried to fix that but playing with that breaks the looks of other apps (e.g. Thunar when unfocused is too gray).

This PR has a lower risk, if it causes any regressions at least they are isolated to Xfdesktop.

**Comment by kelnos** [comment]
> The fallback doesn't work because it is never applied for Greybird or any theme containing XfdesktopIconView.

Ah right, of course, forgot about that.  So the fallback theme isn't relevant here, and you need to actively fix it in greybird, understood.

**Comment by andreldm** [comment]
Ok, let's merge this.

@bluesabre can you please take care of releasing Greybird soon-ish (not urgent)? I believe the packages for Debian/Ubuntu are already patched with this fix.

**Pull request merged**
