### PR TITLE
Replace GTK 2 scrollbar with the one from Wave 0.2

### PR DESCRIPTION
**Pull request by W4RH4WK**
I replaced the GTK2 scrollbar with a slightly slimmer one from another theme [Wave 0.2](http://seahorsepip.deviantart.com/art/Wave-0-2-190517114)

You can merge it if you like it.

screenshot

### CODE REVIEW

**Comment by ochosi** [comment]
Not planning on changing the scrollbar design atm, but I'll keep this open and pending in case I change my mind. Thanks!

**Comment by W4RH4WK** [comment]
okay, but since the pull-requests refers to my master branch and I'm not sure whether I keep the repo as it is now you might want to store the pull-request as a patch and close it.

**Comment by ochosi** [comment]
Storing a patch only locally is almost never a good idea, I'm pretty sure it'd get lost over time. I guess I can just as well hope that you won't move or delete your repo...

**Comment by W4RH4WK** [comment]
i moved the two commits in question to their own branch. since i cannot edit the pull request source branch (afaik) i'd close this request and open another one with the dedicated branch as source.
otherwise you wont be able merge the it anyway.
is that okay for you? sorry for not using a dedicated branch to begin with.

**Comment by ochosi** [comment]
Sure, no problem!

**Pull request closed without merging**
