### PR TITLE
Upstream changes from Greybird Geeko

### PR DESCRIPTION
**Pull request by Appadeia**
Most notable changes being upstreamed:
- Dark theme 
- Build system change to Meson
  - Build system is noticeably faster (i.e. by the time Autotools finishes configuring, Meson has already built and installed)

### CODE REVIEW

**Comment by Mau-G** [comment]
There is a chance that renaming Greybird to Greybird-Light will make users lose their theme forcing them to reselect it from the settings. This should be tested

**Comment by bluesabre** [comment]
Thanks for the quick PR! A few notes...

@Mau-G It's possible we can continue with Greybird-Light if we add a symbolic link to Greybird. Otherwise, we might prefer to just have Greybird / Greybird-Dark. Adwaita also follows this pattern, Adwaita / Adwaita-dark.

Unit193 in #shimmer also produced this diff: http://paste.openstack.org/show/XOu4GZH5EyVEzHWtlsYV/

It highlights the loss of the following themes:

- Greybird-bright xfce-notify-4.0
- Greybird plank theme (We do still have folks using Plank in Xfce, including myself)
- Greybird ubiquity panel theme (though, this is OK, we no longer display the panel)
- Greybird unity theme (While unity is no longer default, it still receives maintenance updates and has a userbase)

**Comment by ochosi** [comment]
Personally I'd prefer to stick to Greybird / Greybird-dark. Greybird-light suggests that it's something new, which it isn't.

**Comment by ochosi** [comment]
Also, this PR seems to pull in far too much. We don't want the OpenSUSE palette etc., instead I'd prefer to have a single, clean commit that introduces the meson build.

**Comment by Mau-G** [comment]
yes let’s start a clean PR. the openSUSE noise is irrelevant in the commits for this

**Comment by bluesabre** [comment]
Closed, these changes were applied with #256

**Pull request closed without merging**
