### PR TITLE
Add dh-autoreconf to the list of required dependencies

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by jbicha** [comment]
Why do you think `dh-autoreconf` is required to build this project?

**Comment by soc** [comment]
```
./autogen.sh --prefix=$HOME/.local
./autogen.sh: 11: ./autogen.sh: autoreconf: not found
```

**Comment by ochosi** [comment]
@jbicha Since you wrote the make part please let me know if you think it makes sense to merge (I suppose yes)

**Comment by ochosi** [comment]
Humm, so in Ubuntu it's `dh-autoreconf` and in Debian it's just `autoreconf`..?

**Comment by jbicha** [comment]
dh-autoreconf is a helper for the debhelper build tool that uses autoreconf. So all we need is `autoreconf` for any Debian-based distro.

We should probably add it to the Fedora list too, but I haven't tried building there.

**Comment by ochosi** [comment]
@jbicha Are you maybe referring to `autoconf`? (Really can't find a package named `autoreconf` in Ubuntu)

**Comment by jbicha** [comment]
Yes, `autoconf`. I did not read carefully.

**Comment by ochosi** [comment]
Ok great, added `autoconf`.

**Pull request closed without merging**
