### PR TITLE
Gtk 3.20

### PR DESCRIPTION
**Pull request by corsac-s**
Hi,

I got a gtk 3.20 upgrade which broke Greybird (again). I've looked at the warnings and tried to fix the easy ones, but there are more (see https://paste.debian.net/436271/)

Following https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/ I decided to “fork” a new gtk-3.20 folder but I have no idea if it's the right way (it'll end up in a lot of duplicate code).

### CODE REVIEW

**Comment by ochosi** [comment]
Wow, what an unlikely pull-request :)
Oh, hrm, shame, that pastebin is gone already...

In terms of approach, adding a subfolder for 3.20 seems reasonable, I guess I'd also go for that.

As to the state of Greybird with 3.20 and your code - is it usable already or are the warnings to be dealt with?

**Comment by corsac-s** [comment]
Ok so here's a gist (yeah, full github way): https://gist.github.com/corsac-s/52c41f39b152e9d5b1b9ab7693e87405

I think the warnings need to be dealt with, but I'm not completely sure.

**Comment by ochosi** [comment]
Ok, so I tried your branch (e.g. Gedit in Debian with Gtk3.20) but honestly Greybird still looks totally broken, even if there are less warnings. Or is this really working for you visually? (Just a random example, the menus are unusable, no hover, no proper selection etc)

So I'm not sure whether merging this makes sense at all, the theme probably still needs rebasing/rewriting on top of Adwaita 3.20.

**Comment by jristz** [comment]
arc theme and mate themes and now even numix themes are doing some work to fix the gtk3.20 mess, maybe looking the work of they can help here fix the theme (and maybe the other themes too)

**Comment by corsac-s** [comment]
Hi (I apparently can't quote previous messages?)

Greybird is still visually broken, obviously. As indicated, the PR was just a first step in porting the theme to GTK 3.20 and fixing the obvious stuff (as indicated by the console output). I'm definitely not a theme designer, so I have no idea what broke exactly and how to fix it.

**Comment by ochosi** [comment]
Hey, so I looked into the changes yesterday evening and I gotta say: don't spend any more time on fixing errors or warnings like that, it won't help, I'll still have to rewrite it. (The whole CSS nodes thing...)

**Comment by corsac-s** [comment]
Ack.

**Pull request closed without merging**
