### PR TITLE
Fix drop down menus and linked buttons (#265)

### PR DESCRIPTION
**Pull request by andreldm**
Hacky fix for #265, I'm using as temporary workaround until a proper fix is found.

### CODE REVIEW

**Comment by ochosi** [comment]
Hm, is it really just the last element of linked buttons? I think I also saw that sometimes the first button of a linked group is affected (need to test again tomorrow).
Anyway this one I'll really need to fix or at least push your workaround for now, it's highly annoying...

**Comment by andreldm** [comment]
I never noticed this problem with the first button.

Oh, I forgot to mention, this PR is not intended to merged, I just wanted an easy way to get a diff and build locally :sweat_smile:

**Comment by ochosi** [comment]
Here you go (note that the leftmost button should also have rounded corners on the left side)
image

**Comment by andreldm** [comment]
That looks like gedit, I don't know why here it looks so different:
image

And buttons from gtk3-demo's Button Boxes look ok with this patch:
image

**Comment by andreldm** [comment]
Yeah, this fix is not perfect, Session and Startup -> Application Autostart:
image

**Comment by m4u9** [comment]
it would perhaps be worth it trying an older version of greybird to see if the problem disappears. i think the problem started happening after the code was recently rebased?

**Comment by andreldm** [comment]
> it would perhaps be worth it trying an older version of greybird to see if the problem disappears. i think the problem started happening after the code was recently rebased?

Nope, I went back to v3.22.10 (068aaa2f), same problem.

> That looks like gedit, I don't know why here it looks so different:

Now I know, that's due `/Gtk/DialogsUseHeader = false`, with that set and this fix applied gedit's buttons look ok:
image

**Comment by ochosi** [comment]
Fixed in master already

**Pull request closed without merging**
