### PR TITLE
Added xfwm4 Greybird-accessibility-dark

### PR DESCRIPTION
**Pull request by Mau-G**
As promised my first attempt at this theme.

Screenshot_2019-11-09_21-53-57

### CODE REVIEW

**Comment by bluesabre** [comment]
I think the color palette works well, but it appears to be missing the padding and window border of the current accessibility theme.

Screenshot_2019-11-10_11-22-39

**Comment by Mau-G** [comment]
@bluesabre you're right. I've used 24 px instead of 32 px for the titlebar height. I can fix that

**Comment by Mau-G** [comment]
@bluesabre better?
Screenshot_2019-11-11_01-21-32

**Comment by bluesabre** [comment]
That's looking really close! I think the last item is the width of the window broder.

**Comment by Mau-G** [comment]
a) Fully enclosed
thick-top

b) Thinner top border
Screenshot_2019-11-11_12-16-07


b) is a personal preference but I guess a) is more useful for accessibility purposes

**Comment by Mau-G** [comment]
Sorry for the noise. I think only this one should be considered as it has a morse subdle yet visible 3 px border

Screenshot_2019-11-11_12-33-02

**Comment by ochosi** [comment]
That last one looks spot on.
Is the branch/PR reflecting this screenshot already?

**Comment by Mau-G** [comment]
@ochosi yes the last commit in this or represent the last screenshot

**Pull request merged**
