### PR TITLE
Improved Button Backgrounds (less edges between buttons and bar).

### PR DESCRIPTION
**Pull request by RalphBike**

### CODE REVIEW

**Comment by RalphBike** [comment]
Hi Simon, any news on this?

Here are two screenshots to show you the changes:


Version with more contrast:

**Comment by ochosi** [comment]
Sorry for the delay. Any reason why the xpms are not updated like in the previous pull request?

**Comment by RalphBike** [comment]
Hi Simon, I thought you prefer to get everything step by step. Should I have put all changes into one request?
In this request I have fixed the buttons themselves, not format or position. I would commit all other stuff in the following requests, which should be 1-3 more. As you like :)

**Comment by ochosi** [comment]
Ah alright, that's totally fine then!

**Pull request merged**
