### PR TITLE
Pressed color matches theme

### PR DESCRIPTION
**Pull request by Yanpas**
Whatever theme you'll choose - color of pressed button will match it (Mint on screenshot). It worked with classic wm theme, now works with compact theme

### CODE REVIEW

**Comment by knomepasi** [comment]
Hello and thanks for the interest and the pull request!

Looking at the screenshot, it looks like with this change, the pressed state buttons are looking flat instead of the shaded look the buttons have in the other states. If you can make the theme keep the shaded look, we'll gladly look at it again and seriously consider merging.

Cheers,
Pasi

**Comment by Yanpas** [comment]
@knomepasi Hi! Your xpms have very big palete, so editing it in notepad is difficult, I don't know where to add ` s active_color_1` (I replace some colors` "1	c #D7DBDF",` e. g. with `"1	c #D7DBDF s active_color_1",` to make them match the theme) 
The other option is to trim classic Greybird buttons, but they are flat! Here is proof https://github.com/shimmerproject/Greybird/blob/master/xfwm4/close-pressed.xpm So I don't think it's problem that they are flat
PS Maybe you know handy xpm editor?

**Comment by ochosi** [comment]
Thanks for your effort – this would be a welcome change!

The xpms aren't the problem, in those, the icons should be flat. What adds the shading are the png overlay files (those are being displayed on top of the xpms) – see the main xfwm4 decoration for that. Also, if you use the "new" (i.e. nicer/rounder) close icon in this branch for pressed, also port over the other close icons.

Would be great if you could fix that.

**Comment by Yanpas** [comment]
And the tone of compact theme buttons differs from classic, it's lighter... Maybe due to PNGs. In other words compact theme needs total rework, maybe another derivation from classic theme.
Is it the correct task list?:
* <s>Fix color of xpms</s>
* Trim shadind pngs of classic theme and replace compact pngs with them
* Trim CLOSE.xpms and CLOSE.png

**Comment by ochosi** [comment]
Yup, basically the compact theme would need to get all icons (colors, shading) from the main theme ported over. (I created the compact theme a looong time ago and didn't update it after we reworked the main theme, you're right about that.)

Not sure why you mention close.xpm/png separately, this affects all icons alike.

**Comment by Yanpas** [comment]
They are not rounded... yes mentioning them separately was extra. And I'm not sure I'll do it in nearest future :confused:

**Comment by ochosi** [comment]
Well if you ever get to it, it'd be much appreciated!

**Comment by Yanpas** [comment]
@ochosi Done! :smiley: Take a look at #105

**Pull request closed without merging**
