### PR TITLE
Update gtk-widgets.css

### PR DESCRIPTION
**Pull request by johnnada**
Fix header bar subtitle font size
capture-1

### CODE REVIEW

**Comment by ochosi** [comment]
Do you have any reference application that uses those subtitles so I can test your branch? (At the moment I don't have any app with CSD installed that has that)

**Comment by johnnada** [comment]
gnome-disk-utility use it for example.

**Comment by ochosi** [comment]
Humm, unfortunately that one doesn't have a CSD in Ubuntu, seems it has been patched out.

**Comment by johnnada** [comment]
I just did some tests with Xubuntu 15.10 beta 2, gnome-clocks, gnome-weather, gnome-sudoku are using header bar subtitles.

**Comment by ochosi** [comment]
Finally got around to testing this one, thanks for the patch!

**Pull request merged**
