### PR TITLE
fix notebook 2px border

### LINKED ISSUE #184: xfce-terminal has extra pixel border with >1 tab
Full issue described here (incl screenshot).
https://bugs.launchpad.net/bugs/1683857

### PR DESCRIPTION
**Pull request by casta**
This is a proposal to fix #184 
Seems to work well here, not seen any regression elsewhere beside fixing the issue.

### CODE REVIEW

**Comment by ochosi** [comment]
While this patch fixes the problem you describe it also removes the border around all notebooks which looks weird e.g. in xfce4-appearance-settings (or any other Xfce settings dialog that uses notebooks).

**Comment by ochosi** [comment]
screenshot comparison just to make sure.
before:
screenshot_2017-06-12_00-26-16
after:
screenshot_2017-06-12_00-24-34

**Comment by casta** [comment]
Oh yes, I did not catch this side effect…
Indeed, it looks hard to fix without making exception for terminal windows.

There is not such issue with the vast majority of other themes as they use a border to delimit the notebook on the notebook top element, not on the stack. So their border encloses the tabs too.

**Comment by casta** [comment]
I have updated the PR with a new proposal.
The idea is that terminal notebooks does not have the .frame css class. So this can be used to distinguish the behaviour.

Seems to work correctly now: no regression in xfce appearance notebook, and terminal notebooks fixed.

For your review !
Thanks

**Comment by casta** [comment]
fixed some of the warning, but not sure about how to fix the others (and the lasts on bg_color are not from me ;))

**Comment by ochosi** [comment]
Thanks for looking further into this. I wouls say that one looks ok!

If we find out further down the road that frames are used in combination with tabs more, we may have to roll back though.

**Pull request merged**
