### PR TITLE
Improve tabwin highlight

### PR DESCRIPTION
**Pull request by andreldm**

### CODE REVIEW

**Comment by ochosi** [comment]
Hm, I'm not sure about flipping the two.

Maybe if we don't transparentize the bg_color but instead use shade to brighten it the contrast would improve too? (Currently the background of the tabwin "shines through" the currently highlighted item, making it less legible on bright backgrounds)

**Comment by andreldm** [comment]
I don't have any strong opinion on the style, as long as the hovered line doesn't "shine more" than the selected one I'm fine (this is already the case for Adwaita). Maybe screenshots can help with my point.

**Before this PR**
before

**After this PR**
after

**Adwaita**
adwaita

**Comment by andreldm** [comment]
@ochosi any thoughts on this?

**Comment by ochosi** [comment]
Superseded by 8fccf605c5dc8895973fb49642a25bc6de774478

**Pull request closed without merging**
